# Generated by Django 6.0.3 on 2026-05-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_userpublication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_link',
            new_name='link',
        ),
    ]
